import type { Metadata } from "next";
import { CustomThemeProvider } from "@/theme/theme-provider";
import "./globals.css";
import { ebGaramond, inter } from "@/theme/typography";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </head>
      <body className={`${inter.variable} ${ebGaramond.variable} font-sans`}>
        <CustomThemeProvider>{children}</CustomThemeProvider>
      </body>
    </html>
  );
}
